echo Copying video drivers
copy \ll2\system\ega320.drv   %1
copy \ll2\system\mcga320.drv  %1
copy \ll2\system\tandy320.drv %1
copy \ll2\system\pcjr320.drv  %1
copy \ll2\system\cga320c.drv  %1
copy \ll2\system\cga320bw.drv %1
copy \ll2\system\hercmono.drv %1
echo Copying sound drivers
copy \ll2\system\std.drv      %1
copy \ll2\system\jr.drv       %1
copy \ll2\system\adl.drv      %1
copy \ll2\system\imf.drv      %1
copy \ll2\system\mt32.drv     %1
echo Copying keyboard drivers
copy \ll2\system\ibmkbd.drv   %1
copy \ll2\system\tandykbd.drv %1
echo Copying input drivers
copy \ll2\system\joystick.drv %1
