;;;;
;;;;	USERMENU.SC
;;;;	(c) Sierra On-Line, Inc, 1988
;;;;
;;;;	Author: Bob Heitman
;;;;
;;;;	This whole class gets redefined by the application programmer.
;;;;	It exists here as a place-holder, so that references can be made
;;;;	to it.
;;;;
;;;;	Classes:
;;;;		TheMenuBar



(script# MENU)



;MENUBAR -----------------------------------------------------------------------

(class TheMenuBar kindof MenuBar
)

